name: Release

on: push

env:
  NODE_VERION: 12.x

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Use Node.js ${{ env.NODE_VERION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERION }}
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      run: npm install

    - name: Build package
      run: npm run build --if-present

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # - name: Semantic release to NPM
    #   run: npm run semantic-release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Set up registry for GitHub
      uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com/

    - name: Publish to GitHub
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}